## Pandas Case Study - Intro

__Purpose:__ The purpose of this lecture is to use a real-world data set of NBA (National Basketball Association) Game Log Data from 2010 to 2017 to see how we can perform Data Analysis in Python using Pandas extensive capabilities. 

__At the end of this lecture you will be able to:__
> 1. Use Pandas capabilities to perform data analysis on a real-world data set

Here, we will practice our Pandas skills by analyzing a real-world data set - NBA Game Logs from 2010 to 2017. This data was pulled from [this website](https://www.basketball-reference.com/) and contains extensive statistics for every game that was played during the regular season and playoffs during each year included in the date range.

Variables:
- __Tm.Pts__ (Team Points)<br>
- __Opp.Pts__ (Opponent Points)<br>
- __Tm.FGM__ (Team Field Goals Made)<br>
- __Tm.FGA__ (Team Field Goals Attempted)<br>
- __Tm.FG_Perc__ (Team Field Goal Percentage)<br>
- __Tm.3PM__ (Team 3 Points Made)<br>
- __Tm.3PA__ (Team 3 Points Attempted)<br>
- __Tm.3P_Perc__ (Team 3 Point Shot Percentage)<br>
- __Tm.FTM__ (Team Free Throws Made)<br>
- __Tm.FTA__ (Team Free Throws Attempted)<br>
- __Tm.FT_Perc__ (Team Free Throw Percentage)<br>
- __Tm.ORB__ (Team Offensive Rebounds)<br>
- __Tm.TRB__ (Team Total Rebounds)<br>
- __Tm.AST__ (Team Assists)<br>
- __Tm.STL__ (Team Steals)<br>
- __Tm.BLK__ (Team Blocks)<br>
- __Tm.TOV__ (Team Turnover)<br>
- __Tm.PF__ (Team Personal Fouls)<br>
- __Home.Attendance__ (Attendance)<br>
- __Referee1__ (Referee 1)<br>
- __Referee2__ (Referee 2)<br>
- __Referee3__ (Referee 3)<br>
- __Referee4__ (Referee 4)<br>

Notes:
- A sample link for the 2015-16 season for the Boston Celtics is provided [here](https://www.basketball-reference.com/teams/BOS/2016/gamelog/)
- Only team's statistics are included in this data and not the opponent's statistics for each game 
- Each game is entered twice (one entry is when team A is considered the "team" and team B is considered the "opponent" and another entry when team B is considered the "team" and team A is considered the opponent)

# Prepare Data and Environment:

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
nba_df = pd.read_csv("NBA_GameLog_2010_2017.csv")

## Inspect Data

### Dimensions

In [3]:
len(nba_df)

20510

In [4]:
nba_df.shape

(20510, 31)

In [5]:
nba_df.size

635810

### Row Labels

In [6]:
nba_df.index

RangeIndex(start=0, stop=20510, step=1)

### Column Labels

In [7]:
nba_df.columns

Index(['GameType', 'Season', 'Team', 'G', 'Date', 'Home', 'Opp', 'W.L',
       'Tm.Pts', 'Opp.Pts', 'Tm.FGM', 'Tm.FGA', 'Tm.FG_Perc', 'Tm.3PM',
       'Tm.3PA', 'Tm.3P_Perc', 'Tm.FTM', 'Tm.FTA', 'Tm.FT_Perc', 'Tm.ORB',
       'Tm.TRB', 'Tm.AST', 'Tm.STL', 'Tm.BLK', 'Tm.TOV', 'Tm.PF',
       'Home.Attendance', 'Referee1', 'Referee2', 'Referee3', 'Referee4'],
      dtype='object')

In [8]:
print(nba_df.columns.values.tolist())

['GameType', 'Season', 'Team', 'G', 'Date', 'Home', 'Opp', 'W.L', 'Tm.Pts', 'Opp.Pts', 'Tm.FGM', 'Tm.FGA', 'Tm.FG_Perc', 'Tm.3PM', 'Tm.3PA', 'Tm.3P_Perc', 'Tm.FTM', 'Tm.FTA', 'Tm.FT_Perc', 'Tm.ORB', 'Tm.TRB', 'Tm.AST', 'Tm.STL', 'Tm.BLK', 'Tm.TOV', 'Tm.PF', 'Home.Attendance', 'Referee1', 'Referee2', 'Referee3', 'Referee4']

### Data Values

In [9]:
nba_df.values[0:3]

array([['RegularSeason', 2010, 'ATL', 1, '10/28/09', 1, 'IND', 'W', 120,
        109, 46, 87, 0.529, 7, 12, 0.583, 21, 29, 0.7240000000000001, 8,
        35, 30, 16, 6, 10, 25, 17998.0, 'Mike Callahan', 'Olandis Poole',
        'Zach Zarba', nan],
       ['RegularSeason', 2010, 'ATL', 2, '10/30/09', 1, 'WAS', 'W', 100,
        89, 32, 78, 0.41, 5, 20, 0.25, 31, 34, 0.912, 11, 47, 18, 5, 7,
        12, 24, 17079.0, 'Kevin Fehr', 'Derrick Stafford',
        'Gary Zielinski', nan],
       ['RegularSeason', 2010, 'ATL', 3, '11/1/09', 0, 'LAL', 'L', 110,
        118, 40, 89, 0.449, 7, 23, 0.304, 23, 26, 0.885, 14, 40, 21, 8,
        3, 19, 21, 18997.0, 'James Capers', 'Bob Delaney',
        'Mark Lindsay', nan]], dtype=object)

### Data Types

In [10]:
nba_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20510 entries, 0 to 20509
Data columns (total 31 columns):
GameType           20510 non-null object
Season             20510 non-null int64
Team               20510 non-null object
G                  20510 non-null int64
Date               20510 non-null object
Home               20510 non-null int64
Opp                20510 non-null object
W.L                20510 non-null object
Tm.Pts             20510 non-null int64
Opp.Pts            20510 non-null int64
Tm.FGM             20510 non-null int64
Tm.FGA             20510 non-null int64
Tm.FG_Perc         20510 non-null float64
Tm.3PM             20510 non-null int64
Tm.3PA             20510 non-null int64
Tm.3P_Perc         20510 non-null float64
Tm.FTM             20510 non-null int64
Tm.FTA             20510 non-null int64
Tm.FT_Perc         20510 non-null float64
Tm.ORB             20510 non-null int64
Tm.TRB             20510 non-null int64
Tm.AST             20510 non-null int64
Tm.STL             20510 non-null int64
Tm.BLK             20510 non-null int64
Tm.TOV             20510 non-null int64
Tm.PF              20510 non-null int64
Home.Attendance    20508 non-null float64
Referee1           20510 non-null object
Referee2           20510 non-null object
Referee3           20506 non-null object
Referee4           28 non-null object
dtypes: float64(4), int64(18), object(9)
memory usage: 4.9+ MB

In [11]:
nba_df.dtypes

GameType            object
Season               int64
Team                object
G                    int64
Date                object
Home                 int64
Opp                 object
W.L                 object
Tm.Pts               int64
Opp.Pts              int64
Tm.FGM               int64
Tm.FGA               int64
Tm.FG_Perc         float64
Tm.3PM               int64
Tm.3PA               int64
Tm.3P_Perc         float64
Tm.FTM               int64
Tm.FTA               int64
Tm.FT_Perc         float64
Tm.ORB               int64
Tm.TRB               int64
Tm.AST               int64
Tm.STL               int64
Tm.BLK               int64
Tm.TOV               int64
Tm.PF                int64
Home.Attendance    float64
Referee1            object
Referee2            object
Referee3            object
Referee4            object
dtype: object

### Data Quick Look

In [12]:
nba_df.head(10)

,GameType,Season,Team,G,Date,Home,Opp,W.L,Tm.Pts,Opp.Pts,...,Tm.AST,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,Referee1,Referee2,Referee3,Referee4
0,RegularSeason,2010,ATL,1,10/28/09,1,IND,W,120,109,...,30,16,6,10,25,17998.0,Mike Callahan,Olandis Poole,Zach Zarba,NaN
1,RegularSeason,2010,ATL,2,10/30/09,1,WAS,W,100,89,...,18,5,7,12,24,17079.0,Kevin Fehr,Derrick Stafford,Gary Zielinski,NaN
2,RegularSeason,2010,ATL,3,11/1/09,0,LAL,L,110,118,...,21,8,3,19,21,18997.0,James Capers,Bob Delaney,Mark Lindsay,NaN
3,RegularSeason,2010,ATL,4,11/3/09,0,POR,W,97,91,...,21,4,7,11,15,20325.0,Matt Boland,Violet Palmer,Bennett Salvatore,NaN
4,RegularSeason,2010,ATL,5,11/4/09,0,SAC,W,113,105,...,17,2,10,16,20,11751.0,Tony Brothers,Phil Robinson,Eddie F. Rush,NaN
5,RegularSeason,2010,ATL,6,11/6/09,0,CHA,L,83,103,...,10,7,11,7,20,15874.0,Eric Dalen,Ron Garretson,Michael Smith,NaN
6,RegularSeason,2010,ATL,7,11/7/09,1,DEN,W,125,100,...,30,4,9,8,33,17801.0,Mark Ayotte,Eric Lewis,Monty McCutchen,NaN
7,RegularSeason,2010,ATL,8,11/11/09,0,NYK,W,114,101,...,23,7,3,15,19,19699.0,James Capers,Joe Crawford,Mark Lindsay,NaN
8,RegularSeason,2010,ATL,9,11/13/09,0,BOS,W,97,86,...,19,7,6,13,20,18624.0,Derrick Collins,Monty McCutchen,Olandis Poole,NaN
9,RegularSeason,2010,ATL,10,11/14/09,1,NOH,W,121,98,...,27,10,3,14,19,18572.0,Bennie Adams,Phil Robinson,Eddie F. Rush,NaN

In [13]:
nba_df.tail(10)

,GameType,Season,Team,G,Date,Home,Opp,W.L,Tm.Pts,Opp.Pts,...,Tm.AST,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,Referee1,Referee2,Referee3,Referee4
20500,Playoffs,2017,WAS,4,4/24/17,0,ATL,L,101,111,...,19,7,5,14,25,18676.0,Ed Malloy,Ken Mauer,Leroy Richardson,NaN
20501,Playoffs,2017,WAS,5,4/26/17,1,ATL,W,103,99,...,21,8,10,6,20,20356.0,Monty McCutchen,James Williams,Sean Wright,NaN
20502,Playoffs,2017,WAS,6,4/28/17,0,ATL,W,115,99,...,21,16,7,16,22,18849.0,Dan Crawford,John Goble,Bill Spooner,NaN
20503,Playoffs,2017,WAS,7,4/30/17,0,BOS,L,111,123,...,27,6,7,12,14,18624.0,Scott Foster,Courtney Kirkland,Zach Zarba,NaN
20504,Playoffs,2017,WAS,8,5/2/17,0,BOS,L,119,129,...,28,7,10,17,29,18624.0,Marc Davis,Rodney Mott,Tom Washington,NaN
20505,Playoffs,2017,WAS,9,5/4/17,1,BOS,W,116,89,...,26,7,5,9,26,20356.0,Tony Brown,James Capers,Monty McCutchen,NaN
20506,Playoffs,2017,WAS,10,5/7/17,1,BOS,W,121,102,...,29,13,3,19,22,20356.0,Sean Corbin,Dan Crawford,Ron Garretson,NaN
20507,Playoffs,2017,WAS,11,5/10/17,0,BOS,L,101,123,...,21,5,5,12,18,18624.0,Mike Callahan,Ed Malloy,Sean Wright,NaN
20508,Playoffs,2017,WAS,12,5/12/17,1,BOS,W,92,91,...,20,4,7,12,24,20356.0,Tony Brothers,John Goble,Ken Mauer,NaN
20509,Playoffs,2017,WAS,13,5/15/17,0,BOS,L,105,115,...,18,6,4,15,17,18624.0,Monty McCutchen,Derrick Stafford,Zach Zarba,NaN

### Data Summary

In [14]:
nba_df.describe()

,Season,G,Home,Tm.Pts,Opp.Pts,Tm.FGM,Tm.FGA,Tm.FG_Perc,Tm.3PM,Tm.3PA,...,Tm.FTA,Tm.FT_Perc,Tm.ORB,Tm.TRB,Tm.AST,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance
count,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,...,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,20510.000000,20508.000000
mean,2013.531351,38.531399,0.500000,100.392101,100.392101,37.541053,82.744027,0.454865,7.563676,21.310824,...,23.417552,0.758225,10.812287,42.554266,21.739249,7.594393,4.898586,13.675865,20.368893,17628.170080
std,2.303376,24.074224,0.500012,12.145940,12.145940,5.020223,7.339972,0.055971,3.422429,6.859396,...,7.469300,0.102966,3.908189,6.506432,5.041229,2.896030,2.578345,3.823149,4.345522,2522.764796
min,2010.000000,1.000000,0.000000,56.000000,56.000000,16.000000,59.000000,0.246000,0.000000,3.000000,...,1.000000,0.143000,1.000000,17.000000,4.000000,0.000000,0.000000,2.000000,5.000000,7244.000000
25%,2011.000000,17.000000,0.000000,92.000000,92.000000,34.000000,78.000000,0.417000,5.000000,16.000000,...,18.000000,0.692000,8.000000,38.000000,18.000000,6.000000,3.000000,11.000000,17.000000,16187.000000
50%,2014.000000,38.000000,0.500000,100.000000,100.000000,37.000000,82.500000,0.453000,7.000000,21.000000,...,23.000000,0.765000,11.000000,42.000000,22.000000,7.000000,5.000000,13.000000,20.000000,18203.000000
75%,2016.000000,59.000000,1.000000,108.000000,108.000000,41.000000,87.000000,0.493000,10.000000,26.000000,...,28.000000,0.829000,13.000000,47.000000,25.000000,9.000000,6.000000,16.000000,23.000000,19571.000000
max,2017.000000,82.000000,1.000000,152.000000,152.000000,62.000000,129.000000,0.684000,25.000000,61.000000,...,64.000000,1.000000,38.000000,81.000000,47.000000,22.000000,18.000000,29.000000,41.000000,23152.000000

### Format Data

In [15]:
nba_df.head(2)

,GameType,Season,Team,G,Date,Home,Opp,W.L,Tm.Pts,Opp.Pts,...,Tm.AST,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,Referee1,Referee2,Referee3,Referee4
0,RegularSeason,2010,ATL,1,10/28/09,1,IND,W,120,109,...,30,16,6,10,25,17998.0,Mike Callahan,Olandis Poole,Zach Zarba,NaN
1,RegularSeason,2010,ATL,2,10/30/09,1,WAS,W,100,89,...,18,5,7,12,24,17079.0,Kevin Fehr,Derrick Stafford,Gary Zielinski,NaN

In [16]:
# convert to datetime
nba_df['Date'] = pd.to_datetime(nba_df['Date'])

In [17]:
# make index the datetime column for easier indexing
nba_df.set_index("Date", inplace = True)

In [18]:
nba_df.index[0:5]

DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-03',
               '2009-11-04'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [19]:
nba_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 20510 entries, 2009-10-28 to 2017-05-15
Data columns (total 30 columns):
GameType           20510 non-null object
Season             20510 non-null int64
Team               20510 non-null object
G                  20510 non-null int64
Home               20510 non-null int64
Opp                20510 non-null object
W.L                20510 non-null object
Tm.Pts             20510 non-null int64
Opp.Pts            20510 non-null int64
Tm.FGM             20510 non-null int64
Tm.FGA             20510 non-null int64
Tm.FG_Perc         20510 non-null float64
Tm.3PM             20510 non-null int64
Tm.3PA             20510 non-null int64
Tm.3P_Perc         20510 non-null float64
Tm.FTM             20510 non-null int64
Tm.FTA             20510 non-null int64
Tm.FT_Perc         20510 non-null float64
Tm.ORB             20510 non-null int64
Tm.TRB             20510 non-null int64
Tm.AST             20510 non-null int64
Tm.STL             20510 non-null int64
Tm.BLK             20510 non-null int64
Tm.TOV             20510 non-null int64
Tm.PF              20510 non-null int64
Home.Attendance    20508 non-null float64
Referee1           20510 non-null object
Referee2           20510 non-null object
Referee3           20506 non-null object
Referee4           28 non-null object
dtypes: float64(4), int64(18), object(8)
memory usage: 4.9+ MB

In [20]:
nba_df.head(3)

,GameType,Season,Team,G,Home,Opp,W.L,Tm.Pts,Opp.Pts,Tm.FGM,...,Tm.AST,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,Referee1,Referee2,Referee3,Referee4
Date,,,,,,,,,,,,,,,,,,,,,
2009-10-28,RegularSeason,2010,ATL,1,1,IND,W,120,109,46,...,30,16,6,10,25,17998.0,Mike Callahan,Olandis Poole,Zach Zarba,NaN
2009-10-30,RegularSeason,2010,ATL,2,1,WAS,W,100,89,32,...,18,5,7,12,24,17079.0,Kevin Fehr,Derrick Stafford,Gary Zielinski,NaN
2009-11-01,RegularSeason,2010,ATL,3,0,LAL,L,110,118,40,...,21,8,3,19,21,18997.0,James Capers,Bob Delaney,Mark Lindsay,NaN

### Missing Data

In [21]:
# total number of missing values 
np.count_nonzero(nba_df.isnull())

20488

In [22]:
# total number of columns with missing values
np.count_nonzero(np.any(nba_df.isnull(), axis = 0))

3

In [23]:
# total number of rows with missing values
np.count_nonzero(np.any(nba_df.isnull(), axis = 1))

20482

In [24]:
# find column names with nan values 
null_columns = nba_df.columns[nba_df.isnull().any()]
nba_df[null_columns].isnull().sum()

Home.Attendance        2
Referee3               4
Referee4           20482
dtype: int64

In [25]:
# remove the referee4 column since 99% of the data is nan
del nba_df["Referee4"]

In [26]:
# find the rows that had nan values
nba_df[nba_df.isnull().any(axis=1)].loc[:, ["Season", "Team", "G", "Opp", "Home.Attendance", "Referee3"]]

            Season Team   G  Opp  Home.Attendance    Referee3
Date
2015-04-15    2015  BOS  82  MIL              NaN  Ben Taylor
2015-03-08    2015  CHO  61  DET          15673.0         NaN
2017-01-16    2017  DEN  39  ORL          11217.0         NaN
2015-03-08    2015  DET  62  CHO          15673.0         NaN
2015-04-15    2015  MIL  82  BOS              NaN  Ben Taylor
2017-01-16    2017  ORL  43  DEN          11217.0         NaN

In [27]:
# find the average attendance for the 2015 BOS season to impute the missing values
avg_att_2015_BOS = nba_df.loc[(nba_df["Season"] == 2015) & (nba_df["Team"] == "BOS"), "Home.Attendance"].mean()
round(avg_att_2015_BOS, 0)

17762.0

In [28]:
# find the average attendance for the 2015 MIL season to impute the missing values
avg_att_2015_MIL = nba_df.loc[(nba_df["Season"] == 2015) & (nba_df["Team"] == "MIL"), "Home.Attendance"].mean()
round(avg_att_2015_MIL, 0)

16565.0

In [29]:
# impute missing attendance values 
nba_df.loc[(nba_df['Season'] == 2015) & (nba_df['Team'] == "BOS") & (nba_df["Opp"] == "MIL") & (nba_df["G"] == 82), "Home.Attendance"] = avg_att_2015_BOS
nba_df.loc[(nba_df['Season'] == 2015) & (nba_df['Team'] == "MIL") & (nba_df["Opp"] == "BOS") & (nba_df["G"] == 82), "Home.Attendance"] = avg_att_2015_MIL

In [30]:
# find the rows that had nan values
nba_df[nba_df.isnull().any(axis=1)].loc[:, ["Season", "Team", "G", "Opp", "Home.Attendance", "Referee3"]]

            Season Team   G  Opp  Home.Attendance Referee3
Date
2015-03-08    2015  CHO  61  DET          15673.0      NaN
2017-01-16    2017  DEN  39  ORL          11217.0      NaN
2015-03-08    2015  DET  62  CHO          15673.0      NaN
2017-01-16    2017  ORL  43  DEN          11217.0      NaN

"Referee3" is NaN because there was not a third referee in that game, therefore we should leave it as is

### Index Data
#### TODO: There's nothing here -- keep or add?

# Problem Set 1 
## Who refereed on "2017-01-01" (new years day)?

In [31]:
# write your code here 
nba_df.loc["2017-01-01", "Referee1":]

                     Referee1         Referee2          Referee3
Date
2017-01-01         Tony Brown       Pat Fraher  Haywoode Workman
2017-01-01    Derrick Collins        Karl Lane       Rodney Mott
2017-01-01       James Capers  Kane Fitzgerald        Tyler Ford
2017-01-01         Eric Dalen     Scott Foster        Ben Taylor
2017-01-01    Derrick Collins        Karl Lane       Rodney Mott
2017-01-01  Courtney Kirkland     Bill Spooner  Justin Van Duyne
2017-01-01       James Capers  Kane Fitzgerald        Tyler Ford
2017-01-01  Courtney Kirkland     Bill Spooner  Justin Van Duyne
2017-01-01         Tony Brown       Pat Fraher  Haywoode Workman
2017-01-01         Eric Dalen     Scott Foster        Ben Taylor

## How many games were played in January of 2016? Was this different than January of 2017?

In [32]:
# write your code here 
print("{} games in January of 2016".format(len(nba_df.loc[(nba_df.index.year == 2016) & (nba_df.index.month == 1), ])))
print("{} games in January of 2017".format(len(nba_df.loc[(nba_df.index.year == 2017) & (nba_df.index.month == 1), ])))

460 games in January of 2016
446 games in January of 2017

## Which team(s) scored more than 145 points in a game?

In [33]:
# write your code here 
nba_df.loc[nba_df.loc[:, "Tm.Pts"] > 145, "Team"].tolist()

['ATL', 'DET', 'GSW', 'GSW', 'OKC', 'PHO', 'SAS']

## What are the top 5 teams with the most fans in 2017? bottom 5 teams?

In [34]:
# write your code here
games_2017 = nba_df.loc[(nba_df.index.year == 2017), ]
games_2017_sorted = games_2017.sort_values(by = ["Home.Attendance"], ascending = False)

In [35]:
games_2017_sorted.loc[:, ["Team", "Opp", "Home", "Home.Attendance"]].head(10) # games are duplicated

           Team  Opp  Home  Home.Attendance
Date
2017-03-04  CHI  LAC     1          22807.0
2017-03-04  LAC  CHI     0          22807.0
2017-03-30  CLE  CHI     0          22282.0
2017-03-30  CHI  CLE     1          22282.0
2017-03-02  CHI  GSW     1          22253.0
2017-03-02  GSW  CHI     0          22253.0
2017-01-27  MIA  CHI     0          22082.0
2017-01-27  CHI  MIA     1          22082.0
2017-04-01  CHI  ATL     1          22019.0
2017-04-01  ATL  CHI     0          22019.0

In [36]:
games_2017_sorted.loc[:, ["Team", "Opp", "Home", "Home.Attendance"]].tail(10) # games are duplicated

           Team  Opp  Home  Home.Attendance
Date
2017-01-16  ORL  DEN     0          11217.0
2017-01-16  DEN  ORL     1          11217.0
2017-01-30  ORL  MIN     0          11124.0
2017-01-30  MIN  ORL     1          11124.0
2017-01-03  SAC  DEN     0          11018.0
2017-01-03  DEN  SAC     1          11018.0
2017-01-24  UTA  DEN     0          10867.0
2017-01-24  DEN  UTA     1          10867.0
2017-01-09  DAL  MIN     0           9625.0
2017-01-09  MIN  DAL     1           9625.0

## How many 3PT shots did GSW avg per game in 2017? How does this compare to the average for that season?

In [37]:
# write your code here
games_2017 = nba_df.loc[(nba_df.index.year == 2017), ]
GSW_2017 = games_2017.loc[games_2017.loc[:, "Team"] == "GSW", ]
rest_2017 = games_2017.loc[games_2017.loc[:, "Team"] != "GSW", ]

In [38]:
GSW_2017["Tm.3PM"].mean()

12.068965517241379

In [39]:
GSW_2017["Tm.3PA"].mean()

31.275862068965516

In [40]:
rest_2017["Tm.3PA"].mean()

27.19724770642202

# Simple Manipulation:

## Creating new columns 

- Dean Oliver identified the ["Four Factors of Basketball Success"](https://www.basketball-reference.com/about/factors.html):
> 1. Shooting (40%)
> 2. Turnovers (25%)
> 3. Rebounding (20%)
> 4. Free Throws (15%)
- Each of these four factors can be easily computed using the box score statistics given in our data set, such as:

$Free Throws = FTM (Free Throws Made) / FG (Field Goals Attempted)$

$Offensive Rebound Percentage = ORB (Offensive Rebounds) / TRB (Total Rebounds)$

Create 2 new columns in the data and call it `FT_Rate` and `ORB_Perc`

In [41]:
# write your code here
nba_df["FT_Rate"] = nba_df["Tm.FTM"] / nba_df["Tm.FGA"]
nba_df["ORB_Perc"] = nba_df["Tm.ORB"] / nba_df["Tm.TRB"]

In [42]:
nba_df.head(3)

,GameType,Season,Team,G,Home,Opp,W.L,Tm.Pts,Opp.Pts,Tm.FGM,...,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,Referee1,Referee2,Referee3,FT_Rate,ORB_Perc
Date,,,,,,,,,,,,,,,,,,,,,
2009-10-28,RegularSeason,2010,ATL,1,1,IND,W,120,109,46,...,16,6,10,25,17998.0,Mike Callahan,Olandis Poole,Zach Zarba,0.241379,0.228571
2009-10-30,RegularSeason,2010,ATL,2,1,WAS,W,100,89,32,...,5,7,12,24,17079.0,Kevin Fehr,Derrick Stafford,Gary Zielinski,0.397436,0.234043
2009-11-01,RegularSeason,2010,ATL,3,0,LAL,L,110,118,40,...,8,3,19,21,18997.0,James Capers,Bob Delaney,Mark Lindsay,0.258427,0.350000

## Sorting rows

- Sort the data set for Steals ("Tm.STL") in descending order to see which team in which game had the most steals

In [43]:
# write your code here
nba_df.sort_values(by = ["Tm.STL"], ascending = False)

,GameType,Season,Team,G,Home,Opp,W.L,Tm.Pts,Opp.Pts,Tm.FGM,...,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,Referee1,Referee2,Referee3,FT_Rate,ORB_Perc
Date,,,,,,,,,,,,,,,,,,,,,
2009-11-09,RegularSeason,2010,GSW,6,1,MIN,W,146,105,52,...,22,9,12,19,15468.0,Pat Fraher,Steve Javie,Derek Richardson,0.329670,0.289474
2010-10-30,RegularSeason,2011,MEM,3,1,MIN,W,109,89,43,...,22,4,17,25,12753.0,David Jones,Scott Twardoski,Greg Willard,0.161290,0.209302
2016-01-08,RegularSeason,2016,NOP,35,1,IND,L,86,91,31,...,21,5,15,18,16895.0,Mike Callahan,Tyler Ford,David Jones,0.180723,0.216216
2011-01-28,RegularSeason,2011,UTA,47,1,MIN,W,108,100,41,...,20,2,10,18,19911.0,Joe Crawford,Marat Kogut,Tom Washington,0.215054,0.372093
2015-12-08,RegularSeason,2016,HOU,22,0,BRK,L,105,110,39,...,20,3,23,15,13319.0,Mitchell Ervin,David Jones,Bill Spooner,0.146341,0.277778
2015-04-25,Playoffs,2015,MIL,4,1,CHI,W,92,90,34,...,20,6,13,21,18717.0,David Guthrie,Jason Phillips,Zach Zarba,0.172414,0.352941
2016-12-07,RegularSeason,2017,HOU,22,1,LAL,W,134,95,51,...,20,2,20,22,16141.0,Derrick Collins,Pat Fraher,Rodney Mott,0.180851,0.288462
2009-11-07,RegularSeason,2010,BOS,8,0,NJN,W,86,76,31,...,20,3,12,16,16119.0,Joe Forte,Eli Roe,Mark Wunderlich,0.333333,0.081081
2015-04-12,RegularSeason,2015,BOS,80,1,CLE,W,117,78,46,...,20,1,7,22,18624.0,Bill Kennedy,J.T. Orr,James Williams,0.178571,0.157895
2013-11-15,RegularSeason,2014,MIA,9,1,DAL,W,110,104,40,...,19,5,16,15,19772.0,Matt Boland,Ron Garretson,Kevin Scott,0.337838,0.117647
2016-12-22,RegularSeason,2017,GSW,30,0,BRK,W,117,101,47,...,19,7,12,19,17732.0,Steve Anderson,Monty McCutchen,Scott Wall,0.105769,0.215686
2016-04-11,RegularSeason,2016,ORL,81,1,MIL,W,107,98,41,...,19,10,10,15,18374.0,Gediminas Petraitis,Scott Wall,Tom Washington,0.214286,0.333333
2014-03-03,RegularSeason,2014,BRK,58,1,CHI,W,96,80,34,...,19,3,11,18,17732.0,Mark Ayotte,Curtis Blair,Tom Washington,0.287671,0.214286
2014-12-30,RegularSeason,2015,GSW,30,1,PHI,W,126,86,46,...,19,11,14,20,19596.0,Curtis Blair,David Jones,Courtney Kirkland,0.268293,0.190476
2015-11-29,RegularSeason,2016,PHI,18,0,MEM,L,84,92,30,...,18,9,25,29,15322.0,Brent Barnaky,Tony Brothers,Leroy Richardson,0.155844,0.195122
2013-11-04,RegularSeason,2014,GSW,4,0,PHI,W,110,90,41,...,18,7,22,24,11089.0,Tony Brothers,Kevin Cutler,Michael Smith,0.141304,0.240741
2012-01-08,RegularSeason,2012,MEM,8,0,LAL,L,82,90,38,...,18,4,9,18,18997.0,Mark Lindsay,Derrick Stafford,Leon Wood,0.053763,0.264706
2016-01-07,RegularSeason,2016,ATL,37,0,PHI,W,126,98,49,...,18,6,16,23,12611.0,Kevin Cutler,Brian Forte,Michael Smith,0.163043,0.291667
2016-01-13,RegularSeason,2016,LAC,39,1,MIA,W,104,90,40,...,18,5,7,25,19194.0,Derrick Collins,John Goble,David Guthrie,0.138298,0.232558
2017-02-15,RegularSeason,2017,LAC,56,1,ATL,W,99,84,37,...,18,3,16,17,19060.0,Tony Brown,Tre Maddox,Bill Spooner,0.139241,0.125000
2012-12-05,RegularSeason,2013,LAC,18,1,DAL,W,112,90,45,...,18,6,17,17,19060.0,Dan Crawford,Olandis Poole,Sean Wright,0.177778,0.244898
2015-11-23,RegularSeason,2016,SAS,14,1,PHO,W,98,84,42,...,18,3,20,20,18418.0,Ron Garretson,Kevin Scott,Gary Zielinski,0.060976,0.289474
2010-11-05,RegularSeason,2011,MEM,6,0,PHO,L,118,123,45,...,18,7,26,30,16470.0,Scott Foster,Michael Smith,Scott Twardoski,0.229167,0.333333
2015-11-27,RegularSeason,2016,PHI,17,0,HOU,L,114,116,40,...,18,5,12,24,17306.0,Kane Fitzgerald,Jason Phillips,Dedric Taylor,0.216867,0.242424
2017-04-02,RegularSeason,2017,CHO,77,0,OKC,W,113,101,37,...,18,5,16,13,18203.0,Steve Anderson,Mark Lindsay,Tom Washington,0.363636,0.081081
2015-12-02,RegularSeason,2016,LAL,18,0,WAS,W,108,104,41,...,18,3,16,22,20356.0,Tony Brown,David Jones,Karl Lane,0.187500,0.355556
2015-11-06,RegularSeason,2016,BOS,5,1,WAS,W,118,98,44,...,18,5,17,21,18624.0,Brent Barnaky,Joe Crawford,Justin Van Duyne,0.185567,0.283019
2012-02-01,RegularSeason,2012,POR,22,1,CHA,W,112,68,44,...,18,11,17,18,20608.0,Brent Barnaky,John Goble,Tom Washington,0.212500,0.139535
2012-01-13,RegularSeason,2012,POR,11,0,SAS,L,83,99,34,...,18,5,18,22,18581.0,Kevin Cutler,Eric Lewis,Monty McCutchen,0.119048,0.277778
2015-11-02,RegularSeason,2016,HOU,4,1,OKC,W,110,105,41,...,18,7,12,22,17224.0,John Goble,Eric Lewis,Leon Wood,0.213483,0.205882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011-12-26,RegularSeason,2012,ORL,2,1,HOU,W,104,95,44,...,1,4,11,15,18846.0,Dan Crawford,Kane Fitzgerald,Scott Wall,0.084337,0.171429
2013-03-30,RegularSeason,2013,SAC,74,1,LAL,L,98,103,39,...,1,2,11,18,17317.0,Nick Buchert,Derrick Stafford,Zach Zarba,0.151163,0.363636
2012-05-14,Playoffs,2012,LAL,8,0,OKC,L,90,119,35,...,1,3,15,20,18203.0,Tony Brothers,David Guthrie,Greg Willard,0.160494,0.302326
2016-04-23,Playoffs,2016,MIA,3,0,CHO,L,80,96,27,...,1,8,14,20,19604.0,Mike Callahan,James Williams,Sean Wright,0.240506,0.226415
2014-03-19,RegularSeason,2014,BOS,69,1,MIA,W,101,96,39,...,1,2,13,18,18624.0,Bennie Adams,Tony Brothers,Leroy Richardson,0.129870,0.250000
2012-05-04,Playoffs,2012,LAL,3,0,DEN,L,84,99,29,...,1,10,15,19,19155.0,Dan Crawford,Jason Phillips,Michael Smith,0.256410,0.295455
2015-02-08,RegularSeason,2015,SAC,50,1,PHO,W,85,83,34,...,1,5,15,17,17013.0,Bennie Adams,Monty McCutchen,Haywoode Workman,0.173333,0.093023
2017-02-26,RegularSeason,2017,CHO,59,0,LAC,L,121,124,38,...,1,1,16,32,19060.0,Pat Fraher,John Goble,Brett Nansel,0.337500,0.116279
2017-03-13,RegularSeason,2017,UTA,67,1,LAC,W,114,108,41,...,1,3,7,22,19911.0,James Capers,Eric Dalen,Kevin Scott,0.230769,0.190476
2009-10-30,RegularSeason,2010,ORL,2,0,NJN,W,95,85,37,...,1,5,14,18,17525.0,Dick Bavetta,Tony Brothers,Phil Robinson,0.200000,0.187500
2017-04-07,RegularSeason,2017,OKC,79,0,PHO,L,99,120,34,...,1,3,9,26,18055.0,Eric Lewis,J.T. Orr,Zach Zarba,0.260870,0.458333
2015-11-30,RegularSeason,2016,SAC,19,1,DAL,W,112,98,36,...,1,1,11,18,16937.0,Sean Corbin,Kevin Cutler,Bill Spooner,0.392405,0.214286
2011-12-27,RegularSeason,2012,SAC,2,0,POR,L,79,101,31,...,1,4,18,27,20350.0,Curtis Blair,Eric Lewis,Ed Malloy,0.170732,0.333333
2016-02-08,RegularSeason,2016,MIN,53,1,NOP,L,102,116,36,...,0,9,12,23,11926.0,Bill Kennedy,Tre Maddox,Gary Zielinski,0.345679,0.220000
2012-01-29,RegularSeason,2012,LAL,21,0,MIN,W,106,101,40,...,0,7,11,18,17551.0,J.T. Orr,Bill Spooner,Zach Zarba,0.227848,0.170732
2014-03-05,RegularSeason,2014,IND,61,0,CHA,L,87,109,31,...,0,2,18,22,15372.0,Mark Ayotte,David Jones,Eli Roe,0.197368,0.268293
2014-12-22,RegularSeason,2015,UTA,29,0,MEM,W,97,91,34,...,0,5,11,15,16991.0,Brent Barnaky,Tony Brothers,Dedric Taylor,0.266667,0.204082
2011-02-05,RegularSeason,2011,NOH,52,1,LAL,L,95,101,41,...,0,3,10,22,18426.0,Mark Ayotte,Derrick Stafford,Zach Zarba,0.048193,0.261905
2013-03-05,RegularSeason,2013,LAL,61,0,OKC,L,105,122,31,...,0,1,16,21,18203.0,Joe Crawford,Kevin Fehr,David Jones,0.402597,0.347826
2015-02-25,RegularSeason,2015,DAL,60,0,ATL,L,87,104,34,...,0,3,15,18,16126.0,Ron Garretson,Bill Kennedy,Leon Wood,0.175000,0.295455
2012-04-11,RegularSeason,2012,TOR,59,1,PHI,L,75,93,29,...,0,5,9,15,16324.0,Tony Brown,Jason Phillips,Scott Twardoski,0.125000,0.190476
2011-01-22,RegularSeason,2011,ORL,44,0,HOU,W,118,104,46,...,0,7,10,19,18052.0,Curtis Blair,Ed Malloy,Rodney Mott,0.149425,0.239130
2011-01-06,RegularSeason,2011,DEN,35,0,SAC,L,102,122,36,...,0,5,22,30,13184.0,Matt Boland,Scott Foster,James Williams,0.366197,0.266667
2011-02-14,RegularSeason,2011,SAS,55,0,NJN,W,102,85,36,...,0,4,13,20,13433.0,Ed Malloy,Rodney Mott,Haywoode Workman,0.287500,0.240000
2011-01-29,RegularSeason,2011,NJN,48,0,MIL,L,81,91,31,...,0,3,11,21,17173.0,David Jones,Derrick Stafford,Josh Tiven,0.194805,0.263158
2016-01-27,RegularSeason,2016,OKC,48,0,MIN,W,126,123,48,...,0,6,12,25,13337.0,Steve Anderson,Sean Corbin,Leroy Richardson,0.219780,0.319149
2014-03-02,RegularSeason,2014,NYK,60,0,CHI,L,90,109,35,...,0,5,12,23,21739.0,David Jones,Mark Lindsay,Ken Mauer,0.189873,0.272727
2010-02-24,RegularSeason,2010,LAC,57,1,DET,W,97,91,34,...,0,2,13,16,16095.0,Matt Boland,Ken Mauer,Derek Richardson,0.261905,0.375000
2010-01-08,RegularSeason,2010,PHO,37,1,MIA,L,105,109,36,...,0,6,17,21,18422.0,Tony Brothers,Phil Robinson,Eddie F. Rush,0.289157,0.254902
2010-04-11,RegularSeason,2010,POR,80,0,LAL,W,91,88,36,...,0,5,11,23,18997.0,Bob Delaney,Scott Wall,Zach Zarba,0.162500,0.260870

# Advanced Manipulation
## Pivots:

### Problem 8: What 5 teams averaged the most points scored in 2017? (use a Pivot Table)

In [44]:
# write your code here
games_2017 = nba_df.loc[(nba_df.index.year == 2017), ]
pd.pivot_table(games_2017, values = "Tm.Pts", index = "Team", aggfunc = np.mean).sort_values(by = "Tm.Pts", ascending = False).head(5)

          Tm.Pts
Team
GSW   115.448276
DEN   114.326531
HOU   114.137931
WAS   110.746032
CLE   110.711864

### Problem 9: What 5 teams averaged the most points allowed in 2017? (use a Pivot Table)

In [45]:
# write your code here
games_2017 = nba_df.loc[(nba_df.index.year == 2017), ]
pd.pivot_table(games_2017, values = "Opp.Pts", index = "Team", aggfunc = np.mean).sort_values(by = "Opp.Pts", ascending = False).head(5)

         Opp.Pts
Team
PHO   113.604167
LAL   112.543478
DEN   112.244898
BRK   111.260000
ORL   110.916667

## GroupBy:

### Split

In [46]:
# ONE-WAY SPLIT
# group by season
season_groups = nba_df.groupby("Season")
# group by team
team_groups = nba_df.groupby("Team")
# group by season type
season_type_groups = nba_df.groupby("GameType")

In [47]:
# TWO-WAY SPLIT
# group by season and team
season_team_groups = nba_df.groupby(["Season", "Team"], as_index = False)

Do you see any other obvious groups in this data?

In [48]:
season_groups.groups

{2010: DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-03',
                '2009-11-04', '2009-11-06', '2009-11-07', '2009-11-11',
                '2009-11-13', '2009-11-14',
                ...
                '2010-03-30', '2010-03-31', '2010-04-02', '2010-04-04',
                '2010-04-06', '2010-04-07', '2010-04-09', '2010-04-10',
                '2010-04-12', '2010-04-14'],
               dtype='datetime64[ns]', name='Date', length=2624, freq=None),
 2011: DatetimeIndex(['2010-10-27', '2010-10-29', '2010-10-30', '2010-11-02',
                '2010-11-03', '2010-11-05', '2010-11-07', '2010-11-08',
                '2010-11-10', '2010-11-12',
                ...
                '2011-03-28', '2011-03-30', '2011-04-01', '2011-04-03',
                '2011-04-05', '2011-04-06', '2011-04-08', '2011-04-09',
                '2011-04-11', '2011-04-13'],
               dtype='datetime64[ns]', name='Date', length=2622, freq=None),
 2012: DatetimeIndex(['2011-12-27', '2011-12-28', '2011-12-30', '2011-12-31',
                '2012-01-02', '2012-01-03', '2012-01-05', '2012-01-06',
                '2012-01-07', '2012-01-09',
                ...
                '2012-04-09', '2012-04-10', '2012-04-13', '2012-04-14',
                '2012-04-16', '2012-04-18', '2012-04-21', '2012-04-23',
                '2012-04-25', '2012-04-26'],
               dtype='datetime64[ns]', name='Date', length=2148, freq=None),
 2013: DatetimeIndex(['2012-11-02', '2012-11-04', '2012-11-07', '2012-11-09',
                '2012-11-11', '2012-11-12', '2012-11-14', '2012-11-16',
                '2012-11-19', '2012-11-21',
                ...
                '2013-03-31', '2013-04-02', '2013-04-03', '2013-04-06',
                '2013-04-07', '2013-04-09', '2013-04-10', '2013-04-12',
                '2013-04-15', '2013-04-17'],
               dtype='datetime64[ns]', name='Date', length=2628, freq=None),
 2014: DatetimeIndex(['2013-10-30', '2013-11-01', '2013-11-03', '2013-11-05',
                '2013-11-07', '2013-11-09', '2013-11-11', '2013-11-13',
                '2013-11-15', '2013-11-16',
                ...
                '2014-04-22', '2014-04-25', '2014-04-27', '2014-04-29',
                '2014-05-05', '2014-05-07', '2014-05-09', '2014-05-11',
                '2014-05-13', '2014-05-15'],
               dtype='datetime64[ns]', name='Date', length=2638, freq=None),
 2015: DatetimeIndex(['2014-10-29', '2014-11-01', '2014-11-05', '2014-11-07',
                '2014-11-08', '2014-11-10', '2014-11-12', '2014-11-14',
                '2014-11-15', '2014-11-18',
                ...
                '2015-04-18', '2015-04-21', '2015-04-24', '2015-04-26',
                '2015-05-03', '2015-05-05', '2015-05-09', '2015-05-11',
                '2015-05-13', '2015-05-15'],
               dtype='datetime64[ns]', name='Date', length=2622, freq=None),
 2016: DatetimeIndex(['2015-10-27', '2015-10-29', '2015-10-30', '2015-11-01',
                '2015-11-03', '2015-11-04', '2015-11-06', '2015-11-07',
                '2015-11-09', '2015-11-11',
                ...
                '2016-03-27', '2016-03-29', '2016-03-30', '2016-04-01',
                '2016-04-03', '2016-04-06', '2016-04-08', '2016-04-10',
                '2016-04-11', '2016-04-13'],
               dtype='datetime64[ns]', name='Date', length=2632, freq=None),
 2017: DatetimeIndex(['2016-10-27', '2016-10-29', '2016-10-31', '2016-11-02',
                '2016-11-04', '2016-11-05', '2016-11-08', '2016-11-09',
                '2016-11-12', '2016-11-15',
                ...
                '2017-04-24', '2017-04-26', '2017-04-28', '2017-04-30',
                '2017-05-02', '2017-05-04', '2017-05-07', '2017-05-10',
                '2017-05-12', '2017-05-15'],
               dtype='datetime64[ns]', name='Date', length=2596, freq=None)}

In [49]:
team_groups.groups

{'ATL': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-03',
                '2009-11-04', '2009-11-06', '2009-11-07', '2009-11-11',
                '2009-11-13', '2009-11-14',
                ...
                '2017-04-07', '2017-04-09', '2017-04-11', '2017-04-12',
                '2017-04-16', '2017-04-19', '2017-04-22', '2017-04-24',
                '2017-04-26', '2017-04-28'],
               dtype='datetime64[ns]', name='Date', length=714, freq=None),
 'BOS': DatetimeIndex(['2009-10-27', '2009-10-28', '2009-10-30', '2009-11-01',
                '2009-11-03', '2009-11-04', '2009-11-06', '2009-11-07',
                '2009-11-11', '2009-11-13',
                ...
                '2017-04-26', '2017-04-28', '2017-04-30', '2017-05-02',
                '2017-05-04', '2017-05-07', '2017-05-10', '2017-05-12',
                '2017-05-15', '2017-05-17'],
               dtype='datetime64[ns]', name='Date', length=722, freq=None),
 'BRK': DatetimeIndex(['2012-11-03', '2012-11-05', '2012-11-07', '2012-11-09',
                '2012-11-11', '2012-11-13', '2012-11-15', '2012-11-18',
                '2012-11-20', '2012-11-21',
                ...
                '2017-03-26', '2017-03-28', '2017-03-30', '2017-04-01',
                '2017-04-02', '2017-04-04', '2017-04-06', '2017-04-08',
                '2017-04-10', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=435, freq=None),
 'CHA': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-10-31', '2009-11-02',
                '2009-11-06', '2009-11-07', '2009-11-10', '2009-11-11',
                '2009-11-14', '2009-11-16',
                ...
                '2014-04-05', '2014-04-09', '2014-04-11', '2014-04-12',
                '2014-04-14', '2014-04-16', '2014-04-20', '2014-04-23',
                '2014-04-26', '2014-04-28'],
               dtype='datetime64[ns]', name='Date', length=402, freq=None),
 'CHI': DatetimeIndex(['2009-10-29', '2009-10-30', '2009-11-01', '2009-11-03',
                '2009-11-05', '2009-11-07', '2009-11-10', '2009-11-11',
                '2009-11-14', '2009-11-17',
                ...
                '2017-04-06', '2017-04-08', '2017-04-10', '2017-04-12',
                '2017-04-16', '2017-04-18', '2017-04-21', '2017-04-23',
                '2017-04-26', '2017-04-28'],
               dtype='datetime64[ns]', name='Date', length=702, freq=None),
 'CHO': DatetimeIndex(['2014-10-29', '2014-11-01', '2014-11-02', '2014-11-04',
                '2014-11-05', '2014-11-07', '2014-11-09', '2014-11-11',
                '2014-11-14', '2014-11-15',
                ...
                '2017-03-26', '2017-03-28', '2017-03-29', '2017-03-31',
                '2017-04-02', '2017-04-04', '2017-04-05', '2017-04-08',
                '2017-04-10', '2017-04-11'],
               dtype='datetime64[ns]', name='Date', length=253, freq=None),
 'CLE': DatetimeIndex(['2009-10-27', '2009-10-28', '2009-10-30', '2009-10-31',
                '2009-11-03', '2009-11-05', '2009-11-06', '2009-11-11',
                '2009-11-12', '2009-11-14',
                ...
                '2017-04-12', '2017-04-15', '2017-04-17', '2017-04-20',
                '2017-04-23', '2017-05-01', '2017-05-03', '2017-05-05',
                '2017-05-07', '2017-05-17'],
               dtype='datetime64[ns]', name='Date', length=701, freq=None),
 'DAL': DatetimeIndex(['2009-10-27', '2009-10-30', '2009-10-31', '2009-11-03',
                '2009-11-04', '2009-11-07', '2009-11-10', '2009-11-11',
                '2009-11-13', '2009-11-15',
                ...
                '2017-03-27', '2017-03-29', '2017-03-31', '2017-04-02',
                '2017-04-04', '2017-04-05', '2017-04-07', '2017-04-09',
                '2017-04-11', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=688, freq=None),
 'DEN': DatetimeIndex(['2009-10-28', '2009-10-29', '2009-11-01', '2009-11-03',
                '2009-11-04', '2009-11-06', '2009-11-07', '2009-11-10',
                '2009-11-11', '2009-11-13',
                ...
                '2017-03-26', '2017-03-28', '2017-03-31', '2017-04-02',
                '2017-04-04', '2017-04-05', '2017-04-07', '2017-04-09',
                '2017-04-11', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=664, freq=None),
 'DET': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-10-31', '2009-11-03',
                '2009-11-04', '2009-11-06', '2009-11-08', '2009-11-11',
                '2009-11-14', '2009-11-15',
                ...
                '2017-03-24', '2017-03-27', '2017-03-28', '2017-03-30',
                '2017-03-31', '2017-04-05', '2017-04-07', '2017-04-09',
                '2017-04-10', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=644, freq=None),
 'GSW': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-04', '2009-11-06',
                '2009-11-08', '2009-11-09', '2009-11-11', '2009-11-13',
                '2009-11-14', '2009-11-17',
                ...
                '2017-04-16', '2017-04-19', '2017-04-22', '2017-04-24',
                '2017-05-02', '2017-05-04', '2017-05-06', '2017-05-08',
                '2017-05-14', '2017-05-16'],
               dtype='datetime64[ns]', name='Date', length=714, freq=None),
 'HOU': DatetimeIndex(['2009-10-27', '2009-10-28', '2009-10-31', '2009-11-02',
                '2009-11-04', '2009-11-06', '2009-11-10', '2009-11-11',
                '2009-11-13', '2009-11-15',
                ...
                '2017-04-19', '2017-04-21', '2017-04-23', '2017-04-25',
                '2017-05-01', '2017-05-03', '2017-05-05', '2017-05-07',
                '2017-05-09', '2017-05-11'],
               dtype='datetime64[ns]', name='Date', length=685, freq=None),
 'IND': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-03', '2009-11-04',
                '2009-11-06', '2009-11-11', '2009-11-14', '2009-11-17',
                '2009-11-18', '2009-11-20',
                ...
                '2017-04-02', '2017-04-04', '2017-04-06', '2017-04-08',
                '2017-04-10', '2017-04-12', '2017-04-15', '2017-04-17',
                '2017-04-20', '2017-04-23'],
               dtype='datetime64[ns]', name='Date', length=704, freq=None),
 'LAC': DatetimeIndex(['2009-10-27', '2009-10-28', '2009-10-30', '2009-10-31',
                '2009-11-02', '2009-11-06', '2009-11-07', '2009-11-09',
                '2009-11-11', '2009-11-13',
                ...
                '2017-04-08', '2017-04-10', '2017-04-12', '2017-04-15',
                '2017-04-18', '2017-04-21', '2017-04-23', '2017-04-25',
                '2017-04-28', '2017-04-30'],
               dtype='datetime64[ns]', name='Date', length=697, freq=None),
 'LAL': DatetimeIndex(['2009-10-27', '2009-10-30', '2009-11-01', '2009-11-03',
                '2009-11-04', '2009-11-06', '2009-11-08', '2009-11-12',
                '2009-11-13', '2009-11-15',
                ...
                '2017-03-26', '2017-03-28', '2017-03-30', '2017-04-01',
                '2017-04-02', '2017-04-05', '2017-04-07', '2017-04-09',
                '2017-04-11', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=689, freq=None),
 'MEM': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-02',
                '2009-11-04', '2009-11-06', '2009-11-07', '2009-11-10',
                '2009-11-11', '2009-11-14',
                ...
                '2017-04-05', '2017-04-07', '2017-04-09', '2017-04-12',
                '2017-04-15', '2017-04-17', '2017-04-20', '2017-04-22',
                '2017-04-25', '2017-04-27'],
               dtype='datetime64[ns]', name='Date', length=703, freq=None),
 'MIA': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-03',
                '2009-11-04', '2009-11-06', '2009-11-10', '2009-11-12',
                '2009-11-14', '2009-11-17',
                ...
                '2017-03-26', '2017-03-28', '2017-03-29', '2017-03-31',
                '2017-04-02', '2017-04-05', '2017-04-07', '2017-04-08',
                '2017-04-10', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=746, freq=None),
 'MIL': DatetimeIndex(['2009-10-30', '2009-10-31', '2009-11-03', '2009-11-06',
                '2009-11-07', '2009-11-11', '2009-11-14', '2009-11-16',
                '2009-11-18', '2009-11-20',
                ...
                '2017-04-06', '2017-04-08', '2017-04-10', '2017-04-12',
                '2017-04-15', '2017-04-18', '2017-04-20', '2017-04-22',
                '2017-04-24', '2017-04-27'],
               dtype='datetime64[ns]', name='Date', length=663, freq=None),
 'MIN': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-02',
                '2009-11-04', '2009-11-06', '2009-11-08', '2009-11-09',
                '2009-11-11', '2009-11-13',
                ...
                '2017-03-28', '2017-03-30', '2017-04-01', '2017-04-03',
                '2017-04-04', '2017-04-06', '2017-04-07', '2017-04-09',
                '2017-04-11', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=640, freq=None),
 'NJN': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-10-31', '2009-11-02',
                '2009-11-04', '2009-11-06', '2009-11-07', '2009-11-11',
                '2009-11-13', '2009-11-14',
                ...
                '2012-04-06', '2012-04-08', '2012-04-10', '2012-04-13',
                '2012-04-14', '2012-04-16', '2012-04-18', '2012-04-21',
                '2012-04-23', '2012-04-26'],
               dtype='datetime64[ns]', name='Date', length=230, freq=None),
 'NOH': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-02',
                '2009-11-04', '2009-11-06', '2009-11-08', '2009-11-09',
                '2009-11-11', '2009-11-13',
                ...
                '2013-03-29', '2013-03-31', '2013-04-03', '2013-04-05',
                '2013-04-07', '2013-04-09', '2013-04-10', '2013-04-12',
                '2013-04-14', '2013-04-17'],
               dtype='datetime64[ns]', name='Date', length=318, freq=None),
 'NOP': DatetimeIndex(['2013-10-30', '2013-11-01', '2013-11-02', '2013-11-05',
                '2013-11-06', '2013-11-08', '2013-11-10', '2013-11-12',
                '2013-11-13', '2013-11-16',
                ...
                '2017-03-26', '2017-03-27', '2017-03-29', '2017-03-31',
                '2017-04-02', '2017-04-04', '2017-04-07', '2017-04-08',
                '2017-04-11', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=332, freq=None),
 'NYK': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-10-31', '2009-11-02',
                '2009-11-04', '2009-11-06', '2009-11-07', '2009-11-09',
                '2009-11-11', '2009-11-13',
                ...
                '2017-03-25', '2017-03-27', '2017-03-29', '2017-03-31',
                '2017-04-02', '2017-04-04', '2017-04-06', '2017-04-07',
                '2017-04-09', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=661, freq=None),
 'OKC': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-03',
                '2009-11-06', '2009-11-08', '2009-11-10', '2009-11-11',
                '2009-11-14', '2009-11-15',
                ...
                '2017-04-05', '2017-04-07', '2017-04-09', '2017-04-11',
                '2017-04-12', '2017-04-16', '2017-04-19', '2017-04-21',
                '2017-04-23', '2017-04-25'],
               dtype='datetime64[ns]', name='Date', length=736, freq=None),
 'ORL': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-03',
                '2009-11-04', '2009-11-06', '2009-11-08', '2009-11-10',
                '2009-11-11', '2009-11-13',
                ...
                '2017-03-24', '2017-03-27', '2017-03-29', '2017-03-31',
                '2017-04-01', '2017-04-04', '2017-04-06', '2017-04-08',
                '2017-04-10', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=665, freq=None),
 'PHI': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-10-31', '2009-11-03',
                '2009-11-06', '2009-11-08', '2009-11-09', '2009-11-11',
                '2009-11-13', '2009-11-14',
                ...
                '2017-03-26', '2017-03-28', '2017-03-29', '2017-03-31',
                '2017-04-02', '2017-04-04', '2017-04-06', '2017-04-08',
                '2017-04-10', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=658, freq=None),
 'PHO': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-03',
                '2009-11-04', '2009-11-06', '2009-11-08', '2009-11-09',
                '2009-11-11', '2009-11-12',
                ...
                '2017-03-24', '2017-03-26', '2017-03-28', '2017-03-30',
                '2017-04-01', '2017-04-02', '2017-04-05', '2017-04-07',
                '2017-04-09', '2017-04-11'],
               dtype='datetime64[ns]', name='Date', length=656, freq=None),
 'POR': DatetimeIndex(['2009-10-27', '2009-10-29', '2009-10-31', '2009-11-01',
                '2009-11-03', '2009-11-06', '2009-11-08', '2009-11-10',
                '2009-11-11', '2009-11-13',
                ...
                '2017-04-03', '2017-04-04', '2017-04-06', '2017-04-08',
                '2017-04-10', '2017-04-12', '2017-04-16', '2017-04-19',
                '2017-04-22', '2017-04-24'],
               dtype='datetime64[ns]', name='Date', length=683, freq=None),
 'SAC': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-10-31', '2009-11-02',
                '2009-11-04', '2009-11-07', '2009-11-08', '2009-11-10',
                '2009-11-13', '2009-11-17',
                ...
                '2017-03-26', '2017-03-27', '2017-03-29', '2017-03-31',
                '2017-04-01', '2017-04-04', '2017-04-07', '2017-04-09',
                '2017-04-11', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=640, freq=None),
 'SAS': DatetimeIndex(['2009-10-28', '2009-10-29', '2009-10-31', '2009-11-05',
                '2009-11-06', '2009-11-09', '2009-11-11', '2009-11-14',
                '2009-11-18', '2009-11-19',
                ...
                '2017-04-25', '2017-04-27', '2017-05-01', '2017-05-03',
                '2017-05-05', '2017-05-07', '2017-05-09', '2017-05-11',
                '2017-05-14', '2017-05-16'],
               dtype='datetime64[ns]', name='Date', length=745, freq=None),
 'TOR': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-04',
                '2009-11-06', '2009-11-07', '2009-11-09', '2009-11-11',
                '2009-11-13', '2009-11-15',
                ...
                '2017-04-15', '2017-04-18', '2017-04-20', '2017-04-22',
                '2017-04-24', '2017-04-27', '2017-05-01', '2017-05-03',
                '2017-05-05', '2017-05-07'],
               dtype='datetime64[ns]', name='Date', length=681, freq=None),
 'UTA': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-02', '2009-11-03',
                '2009-11-05', '2009-11-07', '2009-11-09', '2009-11-11',
                '2009-11-13', '2009-11-14',
                ...
                '2017-04-18', '2017-04-21', '2017-04-23', '2017-04-25',
                '2017-04-28', '2017-04-30', '2017-05-02', '2017-05-04',
                '2017-05-06', '2017-05-08'],
               dtype='datetime64[ns]', name='Date', length=665, freq=None),
 'WAS': DatetimeIndex(['2009-10-27', '2009-10-30', '2009-10-31', '2009-11-03',
                '2009-11-04', '2009-11-06', '2009-11-08', '2009-11-10',
                '2009-11-14', '2009-11-18',
                ...
                '2017-04-24', '2017-04-26', '2017-04-28', '2017-04-30',
                '2017-05-02', '2017-05-04', '2017-05-07', '2017-05-10',
                '2017-05-12', '2017-05-15'],
               dtype='datetime64[ns]', name='Date', length=674, freq=None)}

In [50]:
season_type_groups.groups

{'Playoffs': DatetimeIndex(['2010-04-17', '2010-04-20', '2010-04-24', '2010-04-26',
                '2010-04-28', '2010-04-30', '2010-05-02', '2010-05-04',
                '2010-05-06', '2010-05-08',
                ...
                '2017-04-24', '2017-04-26', '2017-04-28', '2017-04-30',
                '2017-05-02', '2017-05-04', '2017-05-07', '2017-05-10',
                '2017-05-12', '2017-05-15'],
               dtype='datetime64[ns]', name='Date', length=1312, freq=None),
 'RegularSeason': DatetimeIndex(['2009-10-28', '2009-10-30', '2009-11-01', '2009-11-03',
                '2009-11-04', '2009-11-06', '2009-11-07', '2009-11-11',
                '2009-11-13', '2009-11-14',
                ...
                '2017-03-25', '2017-03-28', '2017-03-29', '2017-03-31',
                '2017-04-02', '2017-04-04', '2017-04-06', '2017-04-08',
                '2017-04-10', '2017-04-12'],
               dtype='datetime64[ns]', name='Date', length=19198, freq=None)}

In [51]:
season_groups.ngroups

8

In [52]:
team_groups.ngroups

33

In [53]:
season_type_groups.ngroups

2

In [54]:
season_groups.first() # first row of each group

,GameType,Team,G,Home,Opp,W.L,Tm.Pts,Opp.Pts,Tm.FGM,Tm.FGA,...,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,Referee1,Referee2,Referee3,FT_Rate,ORB_Perc
Season,,,,,,,,,,,,,,,,,,,,,
2010,RegularSeason,ATL,1,1,IND,W,120,109,46,87,...,16,6,10,25,17998.0,Mike Callahan,Olandis Poole,Zach Zarba,0.241379,0.228571
2011,RegularSeason,ATL,1,0,MEM,W,119,104,42,80,...,7,9,15,20,17519.0,Mike Callahan,Olandis Poole,Sean Wright,0.337500,0.204545
2012,RegularSeason,ATL,1,0,NJN,W,106,70,38,86,...,11,4,12,23,18711.0,Matt Boland,Kevin Fehr,Bill Spooner,0.209302,0.333333
2013,RegularSeason,ATL,1,1,HOU,L,102,109,40,85,...,12,4,13,26,18238.0,Brent Barnaky,Ed Malloy,Sean Wright,0.176471,0.194444
2014,RegularSeason,ATL,1,0,DAL,L,109,118,37,76,...,16,5,17,20,19834.0,James Capers,David Guthrie,Derek Richardson,0.355263,0.151515
2015,RegularSeason,ATL,1,0,TOR,L,102,109,40,80,...,6,8,17,24,19800.0,Curtis Blair,Mike Callahan,Sean Wright,0.112500,0.238095
2016,RegularSeason,ATL,1,1,DET,L,94,106,37,82,...,9,4,15,25,19187.0,Eli Roe,Michael Smith,Zach Zarba,0.146341,0.175000
2017,RegularSeason,ATL,1,1,WAS,W,114,99,44,88,...,13,7,21,19,19049.0,Bennie Adams,Monty McCutchen,Aaron Smith,0.159091,0.269231

In [55]:
team_groups.first()

,GameType,Season,G,Home,Opp,W.L,Tm.Pts,Opp.Pts,Tm.FGM,Tm.FGA,...,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,Referee1,Referee2,Referee3,FT_Rate,ORB_Perc
Team,,,,,,,,,,,,,,,,,,,,,
ATL,RegularSeason,2010,1,1,IND,W,120,109,46,87,...,16,6,10,25,17998.0,Mike Callahan,Olandis Poole,Zach Zarba,0.241379,0.228571
BOS,RegularSeason,2010,1,0,CLE,W,95,89,32,72,...,9,8,14,27,20562.0,Tony Brothers,Steve Javie,Derek Richardson,0.305556,0.157895
BRK,RegularSeason,2013,1,1,TOR,W,107,100,37,81,...,6,5,17,19,17732.0,Matt Boland,Bennett Salvatore,Gary Zielinski,0.333333,0.219512
CHA,RegularSeason,2010,1,0,BOS,L,59,92,23,74,...,6,4,18,23,18624.0,Brian Forte,Scott Foster,Gary Zielinski,0.175676,0.304348
CHI,RegularSeason,2010,1,1,SAS,W,92,85,35,84,...,5,9,9,20,21412.0,Scott Foster,Leon Wood,Sean Wright,0.226190,0.288462
CHO,RegularSeason,2015,1,1,MIL,W,108,106,41,101,...,8,9,10,20,19439.0,James Capers,Eric Lewis,Eli Roe,0.198020,0.300000
CLE,RegularSeason,2010,1,1,BOS,L,89,95,29,70,...,7,9,13,22,20562.0,Tony Brothers,Steve Javie,Derek Richardson,0.357143,0.187500
DAL,RegularSeason,2010,1,1,WAS,L,91,102,30,76,...,6,9,9,20,19871.0,Ron Garretson,Michael Smith,Haywoode Workman,0.355263,0.261905
DEN,RegularSeason,2010,1,1,UTA,W,114,105,43,89,...,5,6,13,25,19155.0,James Capers,Bob Delaney,Leroy Richardson,0.258427,0.333333
DET,RegularSeason,2010,1,0,MEM,W,96,74,37,72,...,5,4,9,27,17212.0,Bennie Adams,Joe Forte,Eddie F. Rush,0.222222,0.256410
GSW,RegularSeason,2010,1,1,HOU,L,107,108,44,89,...,7,8,16,22,19596.0,Tony Brown,Dan Crawford,John Goble,0.168539,0.317073
HOU,RegularSeason,2010,1,0,POR,L,87,96,30,81,...,12,2,16,26,20403.0,Derrick Collins,Monty McCutchen,Rodney Mott,0.271605,0.303030
IND,RegularSeason,2010,1,0,ATL,L,109,120,39,73,...,1,4,25,26,17998.0,Mike Callahan,Olandis Poole,Zach Zarba,0.287671,0.150000
LAC,RegularSeason,2010,1,0,LAL,L,92,99,39,87,...,10,4,20,27,18997.0,Bill Kennedy,Leroy Richardson,Bill Spooner,0.126437,0.294118
LAL,RegularSeason,2010,1,1,LAC,W,99,92,35,85,...,13,4,16,15,18997.0,Bill Kennedy,Leroy Richardson,Bill Spooner,0.294118,0.361702
MEM,RegularSeason,2010,1,1,DET,L,74,96,26,72,...,3,3,14,26,17212.0,Bennie Adams,Joe Forte,Eddie F. Rush,0.277778,0.346939
MIA,RegularSeason,2010,1,1,NYK,W,115,93,47,83,...,6,3,16,20,19600.0,Joe Crawford,Mark Lindsay,Jason Phillips,0.168675,0.162791
MIL,RegularSeason,2010,1,0,PHI,L,86,99,34,85,...,7,2,20,27,14638.0,Curtis Blair,Mike Callahan,Bill Kennedy,0.129412,0.272727
MIN,RegularSeason,2010,1,1,NJN,W,95,93,34,93,...,15,2,10,23,18358.0,Marc Davis,Derek Richardson,Mark Wunderlich,0.279570,0.360000
NJN,RegularSeason,2010,1,0,MIN,L,93,95,34,81,...,4,10,22,24,18358.0,Marc Davis,Derek Richardson,Mark Wunderlich,0.308642,0.269231
NOH,RegularSeason,2010,1,0,SAS,L,96,113,39,78,...,5,4,10,19,18581.0,David Guthrie,David Jones,Derrick Stafford,0.166667,0.151515
NOP,RegularSeason,2014,1,1,IND,L,90,95,34,85,...,7,5,15,29,17803.0,Derrick Collins,Eddie F. Rush,Bill Spooner,0.200000,0.348837
NYK,RegularSeason,2010,1,0,MIA,L,93,115,33,87,...,8,3,13,17,19600.0,Joe Crawford,Mark Lindsay,Jason Phillips,0.195402,0.307692
OKC,RegularSeason,2010,1,1,SAC,W,102,89,39,76,...,4,6,12,19,18203.0,Eric Dalen,Ron Garretson,Michael Smith,0.210526,0.195122
ORL,RegularSeason,2010,1,1,PHI,W,120,106,45,81,...,5,6,15,21,17461.0,Joe Derosa,Kevin Fehr,Ed Malloy,0.172840,0.216216
PHI,RegularSeason,2010,1,0,ORL,L,106,120,39,78,...,9,6,13,21,17461.0,Joe Derosa,Kevin Fehr,Ed Malloy,0.269231,0.235294
PHO,RegularSeason,2010,1,0,LAC,W,109,107,41,80,...,6,5,14,20,15974.0,Derrick Collins,Monty McCutchen,Rodney Mott,0.250000,0.277778
POR,RegularSeason,2010,1,1,HOU,W,96,87,33,77,...,9,12,26,27,20403.0,Derrick Collins,Monty McCutchen,Rodney Mott,0.259740,0.235294
SAC,RegularSeason,2010,1,0,OKC,L,89,102,32,79,...,6,5,12,23,18203.0,Eric Dalen,Ron Garretson,Michael Smith,0.278481,0.270270
SAS,RegularSeason,2010,1,1,NOH,W,113,96,45,86,...,4,0,10,22,18581.0,David Guthrie,David Jones,Derrick Stafford,0.162791,0.261905
TOR,RegularSeason,2010,1,1,CLE,W,101,91,34,75,...,4,6,13,30,20152.0,Sean Corbin,Tommy Nunez,Greg Willard,0.373333,0.145833
UTA,RegularSeason,2010,1,0,DEN,L,105,114,37,81,...,3,4,15,20,19155.0,James Capers,Bob Delaney,Leroy Richardson,0.308642,0.256410
WAS,RegularSeason,2010,1,0,DAL,W,102,91,39,84,...,6,4,9,29,19871.0,Ron Garretson,Michael Smith,Haywoode Workman,0.238095,0.195652

### Apply - Aggregate

#### Is it true that 3 Point Attempts have been increasing over the years? 

- Use the `season_groups` GroupBy object that has been created above
- Use the aggregate method of GroupBy objects
- Use `np.sum`
- Sort by `Tm.3pA`

In [56]:
# write your code here
season_groups.aggregate(np.sum).sort_values(by = "Tm.3PA", ascending = False)

,G,Home,Tm.Pts,Opp.Pts,Tm.FGM,Tm.FGA,Tm.FG_Perc,Tm.3PM,Tm.3PA,Tm.3P_Perc,...,Tm.ORB,Tm.TRB,Tm.AST,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,FT_Rate,ORB_Perc
Season,,,,,,,,,,,,,,,,,,,,,
2017,102825,1298,273971,273971,101226,221412,1189.533,25122,70282,925.465,...,26250,112720,58604,19965,12335,34604,51764,4.661692e+07,551.082321,598.915409
2016,103431,1316,269742,269742,100351,222344,1190.931,22524,63673,925.794,...,27426,115037,58252,20562,13046,36078,53478,4.729747e+07,558.573943,621.217785
2015,103254,1311,262324,262324,98251,219265,1177.950,20724,59276,910.596,...,28566,113797,57727,20261,12665,35796,53272,4.696964e+07,546.778771,652.322111
2014,103443,1319,266201,266201,99251,218411,1202.507,20480,56952,942.278,...,28669,112481,57657,20156,12369,36826,54840,4.622591e+07,578.762390,665.735068
2013,103196,1314,257403,257403,97235,215105,1191.132,18808,52569,931.466,...,29237,110600,57694,20376,13444,36542,52548,4.586372e+07,547.153891,688.422815
2010,103301,1312,263091,263091,98508,213747,1212.418,16911,47740,920.197,...,28692,109254,55446,18852,12761,35393,55129,4.534832e+07,612.194228,683.208647
2011,103249,1311,260125,260125,97126,212331,1202.288,16875,47215,924.592,...,28618,108406,55872,19164,12840,35491,54434,4.580788e+07,613.851032,685.980101
2012,67580,1074,206185,206185,78019,174465,962.524,13687,39378,735.484,...,24302,90493,44620,16425,11010,29762,42301,3.742298e+07,455.491303,571.277377

In [57]:
team_groups.aggregate(np.sum).sort_values(by = "Tm.TRB", ascending = False)

,Season,G,Home,Tm.Pts,Opp.Pts,Tm.FGM,Tm.FGA,Tm.FG_Perc,Tm.3PM,Tm.3PA,...,Tm.ORB,Tm.TRB,Tm.AST,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,FT_Rate,ORB_Perc
Team,,,,,,,,,,,,,,,,,,,,,
OKC,1481933,26858,369,77193,73930,28191,60950,341.379,5346,15432,...,8539,33140,15157,5707,4616,10632,15876,1.335388e+07,189.491718,188.265427
SAS,1500096,26908,372,77072,72059,29184,61339,355.497,6005,15712,...,7267,31923,17536,5684,3827,9781,13881,1.350743e+07,156.553623,168.247964
CHI,1413470,26396,351,68550,67297,25856,58314,312.120,4547,12903,...,8401,31561,15579,4822,3863,9400,13388,1.400328e+07,150.002309,186.018688
GSW,1437787,26724,360,76539,73709,28758,61138,336.450,7053,18006,...,7377,30863,17833,6047,3826,10268,15213,1.322449e+07,141.333310,169.833215
IND,1417531,26449,352,69504,68833,25711,57800,313.923,5177,14536,...,7557,30733,14372,5177,3695,9870,14762,1.179658e+07,159.467233,171.098839
MIA,1502024,27145,376,74187,71544,27693,58721,352.700,5429,15046,...,7044,30380,15221,5727,3973,9890,14825,1.426893e+07,172.585658,171.094610
LAL,1387200,26451,345,69261,70659,25805,57666,309.078,5096,14803,...,7835,30114,14690,4952,3379,9369,13497,1.295609e+07,152.031030,177.923008
CLE,1411563,26584,350,70682,70530,26052,57764,316.961,6113,16757,...,7675,29984,15059,4914,2988,9368,13827,1.306689e+07,153.316964,178.355852
HOU,1379348,26308,343,72540,71102,26087,57473,311.635,6898,19467,...,7842,29808,15412,5568,3244,10058,14316,1.192037e+07,163.202194,179.192038
MEM,1415515,26396,351,68801,68194,26236,58155,318.091,3711,10917,...,8276,29730,14453,5942,3310,9202,14474,1.180805e+07,154.795370,193.950831
BOS,1453702,26662,361,71486,70448,26859,58952,330.408,5301,15308,...,6818,29596,16823,5791,3177,9836,15355,1.321647e+07,155.491814,164.101097
ATL,1437656,26458,357,71015,70022,26685,58452,326.688,5910,16556,...,6831,29456,16745,5647,3381,9689,13464,1.203625e+07,144.940763,163.986528
LAC,1403481,26364,349,71511,69817,26568,56964,325.783,5725,16039,...,7277,29352,15895,5594,3549,9242,14677,1.268121e+07,157.071513,172.040697
POR,1375263,26231,340,69270,68772,25664,57087,307.746,5829,16149,...,7678,29289,14522,4613,3141,8978,13617,1.268298e+07,147.024951,178.208945
DEN,1336941,26117,331,69949,69349,25775,56065,305.980,5202,14818,...,7716,29219,15152,5208,3288,9471,14194,1.123139e+07,159.191266,173.620949
WAS,1357189,26244,336,66924,68129,25595,56496,306.057,4587,12837,...,7364,28690,14767,5209,3335,9541,14267,1.161668e+07,134.626264,171.575171
DAL,1385256,26352,343,69561,68841,26038,56904,315.336,5825,16187,...,6656,28521,15395,5273,3128,8755,13542,1.293832e+07,143.255770,159.051829
ORL,1338930,26173,332,65215,66183,24608,54535,300.477,5458,15458,...,6822,28374,14023,4728,3072,9205,13242,1.161867e+07,130.884110,158.342909
TOR,1371312,26335,342,68524,68501,25321,55654,310.637,4962,14057,...,7250,28333,13949,4873,3143,8818,14833,1.213731e+07,160.157265,172.630843
UTA,1338999,26163,332,65667,65583,24605,53657,305.873,4470,12639,...,7410,28154,14430,5079,3580,9201,13980,1.208534e+07,150.656450,173.964257
PHO,1320824,26168,328,67789,68798,25393,55429,301.393,5321,14843,...,7322,28065,14058,4901,3112,9572,14088,1.122765e+07,139.903549,169.735509
MIL,1334978,26112,331,64718,65910,24639,55167,297.011,4575,12918,...,7378,27727,14724,5296,3489,9160,13695,1.074191e+07,132.697964,174.669113
PHI,1324875,26138,328,63585,66728,24259,55122,290.456,4732,13988,...,7095,27687,14430,5480,3337,9386,13471,1.079997e+07,124.721537,167.765080
DET,1296728,26042,322,62848,64663,24013,53951,287.367,4292,12581,...,7954,27670,13192,4703,2724,8409,12692,1.071139e+07,127.644163,184.115481
SAC,1288664,26032,320,64809,67443,24278,53691,290.101,4280,12267,...,7341,27522,13400,4900,2757,9426,13524,1.044765e+07,144.775751,169.374822
NYK,1330924,26135,330,65841,66958,24483,55044,294.628,5703,16037,...,7133,27508,13602,4921,3110,8691,13770,1.241621e+07,135.939201,169.857929
MIN,1288664,26032,320,64493,67046,23999,53658,286.916,3977,11695,...,7549,27400,13992,5021,2777,9318,12662,1.039522e+07,151.211467,174.938491
BRK,876499,17142,217,43243,44605,16073,35632,196.688,3473,9967,...,4456,18200,9172,3273,1854,6165,8579,7.461341e+06,94.274145,105.395879
CHA,808824,15843,201,37515,39492,13983,31926,176.517,2151,6449,...,4143,16322,8237,2682,2176,5382,7725,6.483533e+06,94.767550,100.977703
NOP,669144,13622,166,33706,34378,12724,28064,150.922,2569,7118,...,3406,14229,7331,2500,1850,4231,6685,5.692536e+06,68.376489,78.759399
NOH,639646,12441,159,30170,30907,11574,25381,145.311,1836,5139,...,3434,12924,6729,2300,1433,4212,6464,5.063755e+06,65.992022,83.304882
CHO,510048,10237,126,25433,25516,9265,21417,109.604,2235,6453,...,2325,11048,5418,1705,1299,2846,4463,4.442731e+06,55.737394,52.812005
NJN,462514,9017,115,21441,23096,7993,18512,99.550,1343,4003,...,2589,9266,4574,1524,1037,3120,4718,3.518354e+06,51.767071,63.869322

#### Is it true that teams play "better" in the playoffs? Does the attendance reflect this? 

- Use the `season_type` GroupBy object that has been created above
- Use the aggregate method of GroupBy objects
- Use `np.mean`

In [58]:
# write your code here 
season_type_groups.aggregate(np.mean)

,Season,G,Home,Tm.Pts,Opp.Pts,Tm.FGM,Tm.FGA,Tm.FG_Perc,Tm.3PM,Tm.3PA,...,Tm.ORB,Tm.TRB,Tm.AST,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,FT_Rate,ORB_Perc
GameType,,,,,,,,,,,,,,,,,,,,,
Playoffs,2013.440549,7.227896,0.5,97.857470,97.857470,35.762957,80.457317,0.445668,7.676829,22.035823,...,10.515244,41.823171,19.783537,7.179116,5.016006,12.702744,21.745427,19269.474085,0.235306,0.248752
RegularSeason,2013.537556,40.670695,0.5,100.565319,100.565319,37.662569,82.900302,0.455494,7.555943,21.261277,...,10.832587,42.604230,21.872903,7.622773,4.890562,13.742369,20.274820,17515.954259,0.216437,0.252147

#### Were the the 2017 Warriors the best team of all time (well, in the last 10 years since that is what our data is)? 

- Use the `season_team_groups` GroupBy object that has been created above
- Use the aggregate method of GroupBy objects
- Use `np.mean`
- Sort by `Tm.Pts` and other variables to see if they lead the pack in all categories

In [59]:
season_team_groups.aggregate(np.mean).sort_values(by = "Tm.Pts", ascending = False).head(5)

,Season,Team,G,Home,Tm.Pts,Opp.Pts,Tm.FGM,Tm.FGA,Tm.FG_Perc,Tm.3PM,...,Tm.ORB,Tm.TRB,Tm.AST,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,FT_Rate,ORB_Perc
219,2017,GSW,37.586957,0.510870,116.021739,103.804348,42.956522,86.891304,0.495565,11.978261,...,9.282609,44.543478,30.108696,9.521739,6.826087,14.228261,19.402174,19353.630435,0.210303,0.207440
220,2017,HOU,37.301075,0.505376,114.440860,109.215054,39.946237,86.956989,0.460108,14.215054,...,10.763441,44.204301,24.569892,8.118280,4.322581,14.333333,20.043011,17632.107527,0.236561,0.242830
189,2016,GSW,34.933962,0.518868,113.264151,103.952830,41.726415,86.924528,0.480802,13.047170,...,10.075472,45.518868,27.886792,8.301887,5.933962,14.575472,21.018868,19379.528302,0.194726,0.219635
217,2017,DEN,41.500000,0.500000,111.719512,111.207317,41.182927,87.731707,0.470890,10.609756,...,11.780488,46.365854,25.329268,6.926829,3.951220,14.451220,19.109756,16095.378049,0.217549,0.251720
215,2017,CLE,37.890110,0.494505,110.780220,106.923077,39.912088,84.538462,0.472901,13.109890,...,9.285714,43.560440,22.538462,6.637363,4.131868,13.120879,18.098901,19783.857143,0.212903,0.212009

In [60]:
season_team_groups.aggregate(np.mean).sort_values(by = "Tm.3PM", ascending = False).head(5)

,Season,Team,G,Home,Tm.Pts,Opp.Pts,Tm.FGM,Tm.FGA,Tm.FG_Perc,Tm.3PM,...,Tm.ORB,Tm.TRB,Tm.AST,Tm.STL,Tm.BLK,Tm.TOV,Tm.PF,Home.Attendance,FT_Rate,ORB_Perc
220,2017,HOU,37.301075,0.505376,114.440860,109.215054,39.946237,86.956989,0.460108,14.215054,...,10.763441,44.204301,24.569892,8.118280,4.322581,14.333333,20.043011,17632.107527,0.236561,0.242830
215,2017,CLE,37.890110,0.494505,110.780220,106.923077,39.912088,84.538462,0.472901,13.109890,...,9.285714,43.560440,22.538462,6.637363,4.131868,13.120879,18.098901,19783.857143,0.212903,0.212009
189,2016,GSW,34.933962,0.518868,113.264151,103.952830,41.726415,86.924528,0.480802,13.047170,...,10.075472,45.518868,27.886792,8.301887,5.933962,14.575472,21.018868,19379.528302,0.194726,0.219635
211,2017,BOS,36.541667,0.510417,107.843750,105.229167,38.677083,84.885417,0.456333,12.156250,...,9.104167,41.458333,25.593750,7.552083,4.177083,12.625000,20.625000,18608.656250,0.217504,0.218606
219,2017,GSW,37.586957,0.510870,116.021739,103.804348,42.956522,86.891304,0.495565,11.978261,...,9.282609,44.543478,30.108696,9.521739,6.826087,14.228261,19.402174,19353.630435,0.210303,0.207440

#### What team in what season had the hardest path to the finals (i.e. most games needed)? 

- Use the `season_team_groups` object that was created above 
- Use the `size()` method of GroupBy objects

In [61]:
season_team_groups.size().sort_values(ascending=False).head(5)

Season  Team
2016    GSW     106
2010    BOS     106
        LAL     105
2014    SAS     105
2013    MIA     105
dtype: int64

#### What are the most common referee pairings? 

- Create a new GroupBy object with referees
- Sort values in descending order

In [62]:
referee_1_groups = nba_df.groupby(["Referee1", "Referee2", "Referee3"])
referee_1_groups.size().sort_values(ascending = False).head(30)

Referee1           Referee2           Referee3
Brian Forte        Ed Malloy          Ken Mauer           16
Mike Callahan      Josh Tiven         Sean Wright         16
                   Derrick Collins    Olandis Poole       14
                   Jason Phillips     Olandis Poole       14
Ron Garretson      Marat Kogut        Leon Wood           14
Eli Roe            Derrick Stafford   Zach Zarba          14
Curtis Blair       Eric Lewis         Bill Spooner        14
Pat Fraher         Monty McCutchen    Tommy Nunez         14
Tony Brown         Dan Crawford       John Goble          12
Marc Davis         David Guthrie      Derek Richardson    12
James Capers       Derrick Collins    Olandis Poole       12
Derrick Collins    Joe Crawford       Mark Lindsay        12
James Capers       Jason Phillips     Zach Zarba          12
Marc Davis         Courtney Kirkland  Scott Twardoski     12
Bill Kennedy       Eli Roe            Zach Zarba          12
Scott Foster       Leon Wood          Sean Wright         12
                   John Goble         Bill Kennedy        12
Derrick Collins    Scott Foster       James Williams      12
Kevin Fehr         David Jones        Derrick Stafford    12
Mark Ayotte        Bill Spooner       Zach Zarba          12
Pat Fraher         Ron Garretson      Derek Richardson    12
Tony Brothers      Phil Robinson      Eddie F. Rush       12
Dan Crawford       Marc Davis         Jason Phillips      12
Sean Corbin        Dan Crawford       Kevin Fehr          12
Courtney Kirkland  Ed Malloy          Ken Mauer           12
Eric Lewis         J.T. Orr           Bill Spooner        12
Pat Fraher         Derek Richardson   Mark Wunderlich     12
Rodney Mott        Bill Spooner       Haywoode Workman    10
David Guthrie      David Jones        Derrick Stafford    10
Pat Fraher         Eddie F. Rush      Haywoode Workman    10
dtype: int64

### Apply - Transform

#### Add a column to include the team's points range 

- Use the `team_groups` GroupBy object that was created above
- Use the `transform` feature of GroupBy objects with `max` and `min` to compute the range
- Add this as a new column called `Points_Range`
- Show different teams to see how their range differs

In [ ]:
nba_df["Points_Range"] = team_groups["Tm.Pts"].transform('max') - team_groups["Tm.Pts"].transform('min')
nba_df.iloc[1:5, ]

In [ ]:
nba_df.iloc[1001:1005, ]